#def reverse(array):
#   for in in range(0, int(lenarray)/2)):------->O(N/2) ---->O(N)
#     other = len(array)-i-1  ------------->O(1)
#     temp = array[i]      ---------------------->O(1)
#     araay[i] = array[other]------------------>O(1)
#     array[other] = temp------------------------>O(1)
# print(array)---------------------------------->O(1)
#Time complexity = O(N)



#        input                      output
#|1|2|3|4|5|   ---------------> |5|4|3|2|1|
#Question
# WHich of the following are equivalent to O(N)? Why?(Use time complexity graph)
# 1. O(N+P), WHERE P < N/2    ------------------->  o(n) correct
# 2. O(2N)  -----------------------------> o(n)  correct
# 3.O(N+LOGN) --------------------> o(n)  correct
# 4.O(N+ N LOGN)-------------> o(Nlogn)  weong
# 5.O(N+M)---------->no relation btween in N AND M SO wrong
